# Generated by Django 4.1 on 2022-09-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='comida',
            field=models.TextField(null=True, verbose_name='Comida'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico',
            field=models.CharField(max_length=100, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='habitacion',
            field=models.IntegerField(null=True, verbose_name='Habitación'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
